### ISSUE TITLE
Selecting a class from the dropdown does not change the requirement to green.

### ISSUE THREAD

**Issue by RyanLoringCooper** [COEN174/MainProject#57]
Same with changing it yellow when a quarter is scheduled. Are there onSelectListeners that we could put on the dropdowns to do stuff?

**Comment by jkingsman** [comment]
Ignore the accidental closure here; that commit had nothing to do with this issue.

**Comment by jkingsman** [comment]
The quarter dropdown seems to do this and move it to yellow but I agree that the class selection should do that. Let's discuss priorities for what needs to be done before the demo tonight; since we control the demo I think we can be perhaps less bulletproof on everything that we would if Atkinson was banging on it.
